name: service_locator_workshop
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
  benchmark_harness: ^2.2.2
  get_it: ^7.6.0
  ioc_container: ^1.0.12
